// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzyhnVZ1Ii_rJ9O9iwgWPUzmSv5Mo5gWY',
    appId: '1:507128691022:web:0bad46819a721f50a3c61f',
    messagingSenderId: '507128691022',
    projectId: 'practice-dart-ui-app',
    authDomain: 'practice-dart-ui-app.firebaseapp.com',
    storageBucket: 'practice-dart-ui-app.firebasestorage.app',
    measurementId: 'G-QYREC2FQSW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcqZUaJYWhIwRNEvOtwlWXA1CkLRyj-s0',
    appId: '1:507128691022:android:41d67dc34c42725aa3c61f',
    messagingSenderId: '507128691022',
    projectId: 'practice-dart-ui-app',
    storageBucket: 'practice-dart-ui-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKgN-_nQSIHnbeQPo0pofBkyJZo0m2UY4',
    appId: '1:507128691022:ios:8455469666194d58a3c61f',
    messagingSenderId: '507128691022',
    projectId: 'practice-dart-ui-app',
    storageBucket: 'practice-dart-ui-app.firebasestorage.app',
    iosBundleId: 'com.example.practiceDartUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKgN-_nQSIHnbeQPo0pofBkyJZo0m2UY4',
    appId: '1:507128691022:ios:8455469666194d58a3c61f',
    messagingSenderId: '507128691022',
    projectId: 'practice-dart-ui-app',
    storageBucket: 'practice-dart-ui-app.firebasestorage.app',
    iosBundleId: 'com.example.practiceDartUi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzyhnVZ1Ii_rJ9O9iwgWPUzmSv5Mo5gWY',
    appId: '1:507128691022:web:2e1dbe39a2ad7259a3c61f',
    messagingSenderId: '507128691022',
    projectId: 'practice-dart-ui-app',
    authDomain: 'practice-dart-ui-app.firebaseapp.com',
    storageBucket: 'practice-dart-ui-app.firebasestorage.app',
    measurementId: 'G-WJ0W7C5799',
  );
}
